import type { Metadata } from "next";
import Header from "./layout/header/Header";
import "./ui/globals.css";
import "./ui/fonts"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
