# Generated by Django 5.2 on 2025-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='cargo',
            field=models.CharField(choices=[('Director Técnico', 'Director Técnico'), ('Preparador Físico', 'Preparador Físico'), ('Nutricionista', 'Nutricionista')], max_length=50),
        ),
    ]
