# Generated by Django 5.2 on 2025-05-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0003_alter_entrenador_trainer_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='trainer_foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
