# Generated by Django 5.2 on 2025-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0004_alter_entrenador_trainer_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='cargo',
            field=models.CharField(choices=[('director_tecnico', 'Director Técnico'), ('entrenador_principal', 'Entrenador Principal'), ('preparador_fisico', 'Preparador Físico'), ('segundo_entrenador', 'Segundo Entrenador'), ('cutman', 'Cutman'), ('nutricionista', 'Nutricionista'), ('psicologo', 'Psicólogo Deportivo'), ('manager', 'Mánager Deportivo'), ('asistente_tecnico', 'Asistente Técnico'), ('kinesiologo', 'Kinesiólogo / Fisioterapeuta'), ('sparring', 'Preparador de Sparring'), ('analista', 'Analista de Rendimiento')], max_length=50),
        ),
    ]
