# Generated by Django 5.2 on 2025-07-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0012_rename_status_boxeador_estado_and_more'),
        ('entrenador', '0005_alter_entrenador_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='trainer_foto',
            new_name='foto_entrenador',
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='n_licencia',
        ),
        migrations.AddField(
            model_name='entrenador',
            name='boxeador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxeador.boxeador'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='licencia',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='provincias',
            field=models.CharField(choices=[('CABA', 'Ciudad Autónoma de Buenos Aires'), ('PBA', 'Buenos Aires'), ('CT', 'Catamarca'), ('CHC', 'Chaco'), ('CHB', 'Chubut'), ('CD', 'Córdoba'), ('CR', 'Corrientes'), ('ER', 'Entre Ríos'), ('FM', 'Formosa'), ('JJ', 'Jujuy'), ('LP', 'La Pampa'), ('LP', 'La Rioja'), ('MZ', 'Mendoza'), ('MS', 'Misiones'), ('NQ', 'Neuquén'), ('RN', 'Río Negro'), ('ST', 'Salta'), ('SJ', 'San Juan'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SE', 'Santiago del Estero'), ('TF', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'), ('TC', 'Tucumán')], default='Sin provincias', max_length=200),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='cargo',
            field=models.CharField(choices=[('director tecnico', 'Director Técnico'), ('entrenador principal', 'Entrenador Principal'), ('preparador fisico', 'Preparador Físico'), ('segundo entrenador', 'Segundo Entrenador'), ('cutman', 'Cutman'), ('nutricionista', 'Nutricionista'), ('psicologo', 'Psicólogo Deportivo'), ('manager', 'Mánager Deportivo'), ('asistente_tecnico', 'Asistente Técnico'), ('kinesiologo', 'Kinesiólogo / Fisioterapeuta'), ('sparring', 'Preparador de Sparring'), ('analista', 'Analista de Rendimiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='localidad',
            field=models.CharField(default='Sin localidad', max_length=200),
        ),
    ]
