# Generated by Django 5.2 on 2025-05-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxeador', '0006_remove_boxeador_derrotas_remove_boxeador_empates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('peso', models.FloatField()),
                ('lugar', models.CharField(max_length=200)),
                ('resultados', models.CharField(choices=[('Victorias', [('KOS', 'Victoria por nocaut'), ('TKO', 'Victoria por nocaut técnico'), ('RSC', 'Parada del árbitro (amateur)'), ('UD', 'Decisión unánime'), ('PTS', 'Decisión por puntos'), ('IDT', 'Gana por retiro'), ('TDU', 'Decisión técnica unánime'), ('TDM', 'Decisión técnica por mayoría')]), ('Derrotas', [('DQ', 'Descalificación'), ('DDQ', 'Doble descalificación'), ('RET', 'Retiro (aficionado)'), ('TDS', 'Decisión técnica dividida'), ('AB', 'Renuncia en esquina (amateur)')]), ('Empates', [('MD', 'Decisión mayoritaria'), ('SD', 'Decisión dividida'), ('TDD', 'Empate técnico')]), ('SinDec', [('NC', 'Sin concurso'), ('ND', 'Sin decisión'), ('BYE', 'Bye de ronda (amateur)'), ('WO', 'Walk Over (amateur)')]), ('Otros', [('VS', 'Versus / pelea programada')])], max_length=6)),
                ('boxeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_principal', to='boxeador.boxeador')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combate_rival', to='boxeador.boxeador')),
            ],
        ),
    ]
