# Generated by Django 5.2 on 2025-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combates',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
