# Generated by Django 5.2 on 2025-07-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combates', '0002_combates_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combates',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='combates',
            name='rounds',
        ),
    ]
