# Generated by Django 5.2 on 2025-04-18 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('numero_licencia', models.CharField(max_length=10, unique=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('debutaje', models.DateField()),
                ('carrera', models.DateField()),
                ('peso', models.FloatField()),
                ('divicion', models.CharField(choices=[('Peso Mosca', 'Peso Mosca'), ('Peso Gallo', 'Peso Gallo'), ('Peso Pluma', 'Peso Pluma'), ('Peso Ligero', 'Peso Ligero'), ('Peso Welter', 'Peso Welter'), ('Peso Medio', 'Peso Medio'), ('Peso Supermedio', 'Peso Supermedio'), ('Peso Semipesado', 'Peso Semipesado'), ('Peso Crucero', 'Peso Crucero'), ('Peso Pesado', 'Peso Pesado')], max_length=50)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=50)),
                ('combates', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('KOs', models.IntegerField(default=0)),
                ('altura', models.FloatField()),
                ('alcance', models.FloatField()),
                ('stance', models.CharField(choices=[('Ortodoxo', 'Ortodoxo'), ('Zurdo', 'Zurdo'), ('Switch', 'Switch')], max_length=50)),
                ('victorias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('derrotas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('empates', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sin_definir', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='boxeadores/fotos/')),
            ],
        ),
    ]
