# Generated by Django 5.2 on 2025-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeador',
            name='derrotas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='empates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='sin_definir',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='victorias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
