# Generated by Django 5.2 on 2025-04-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0002_alter_boxeador_derrotas_alter_boxeador_empates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxeador',
            name='foto',
        ),
    ]
