# Generated by Django 5.2 on 2025-04-20 14:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0003_remove_boxeador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxeador',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
