# Generated by Django 5.2 on 2025-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0004_boxeador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeador',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Retirado', 'Retirado')], default='Activo', max_length=50),
        ),
    ]
