# Generated by Django 5.2 on 2025-05-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0005_alter_boxeador_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxeador',
            name='derrotas',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='empates',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='sin_definir',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='victorias',
        ),
    ]
