# Generated by Django 5.2 on 2025-05-30 17:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0006_remove_boxeador_derrotas_remove_boxeador_empates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeador',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
