# Generated by Django 5.2 on 2025-05-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0007_alter_boxeador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeador',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
