# Generated by Django 5.2 on 2025-06-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0008_alter_boxeador_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxeador',
            old_name='foto',
            new_name='boxer_foto',
        ),
        migrations.RenameField(
            model_name='boxeador',
            old_name='divicion',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='boxeador',
            old_name='numero_licencia',
            new_name='n_licencia',
        ),
    ]
