# Generated by Django 5.2 on 2025-06-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0009_rename_foto_boxeador_boxer_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxeador',
            name='KOs',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='combates',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='rounds',
        ),
    ]
