# Generated by Django 5.2 on 2025-07-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeador', '0011_remove_boxeador_nacionalidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxeador',
            old_name='status',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='boxeador',
            old_name='boxer_foto',
            new_name='foto_boxeador',
        ),
        migrations.RenameField(
            model_name='boxeador',
            old_name='carrera',
            new_name='nacimiento',
        ),
        migrations.RenameField(
            model_name='boxeador',
            old_name='stance',
            new_name='postura_combate',
        ),
        migrations.RenameField(
            model_name='boxeador',
            old_name='debutaje',
            new_name='vencimiento',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='n_licencia',
        ),
        migrations.RemoveField(
            model_name='boxeador',
            name='provincia',
        ),
        migrations.AddField(
            model_name='boxeador',
            name='licencia',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='boxeador',
            name='provincias',
            field=models.CharField(choices=[('CABA', 'Ciudad Autónoma de Buenos Aires'), ('PBA', 'Buenos Aires'), ('CT', 'Catamarca'), ('CHC', 'Chaco'), ('CHB', 'Chubut'), ('CD', 'Córdoba'), ('CR', 'Corrientes'), ('ER', 'Entre Ríos'), ('FM', 'Formosa'), ('JJ', 'Jujuy'), ('LP', 'La Pampa'), ('LP', 'La Rioja'), ('MZ', 'Mendoza'), ('MS', 'Misiones'), ('NQ', 'Neuquén'), ('RN', 'Río Negro'), ('ST', 'Salta'), ('SJ', 'San Juan'), ('SL', 'San Luis'), ('SC', 'Santa Cruz'), ('SF', 'Santa Fe'), ('SE', 'Santiago del Estero'), ('TF', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'), ('TC', 'Tucumán')], default='Sin provincias', max_length=200),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='localidad',
            field=models.CharField(default='Sin localidad', max_length=200),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
    ]
